package tw.ktrssreader.parser

object ParserConst {
    const val CHANNEL = "channel"
    const val TITLE = "title"
    const val DESCRIPTION = "description"
    const val IMAGE = "image"
    const val LANGUAGE = "language"
    const val CATEGORY = "category"
    const val LINK = "link"
    const val COPYRIGHT = "copyright"
    const val MANAGING_EDITOR = "managingEditor"
    const val WEB_MASTER = "webMaster"
    const val PUB_DATE = "pubDate"
    const val LAST_BUILD_DATE = "lastBuildDate"
    const val GENERATOR = "generator"
    const val DOCS = "docs"
    const val CLOUD = "cloud"
    const val TTL = "ttl"
    const val RATING = "rating"
    const val TEXT_INPUT = "textInput"
    const val SKIP_HOURS = "skipHours"
    const val SKIP_DAYS = "skipDays"
    const val ITEM = "item"
    const val URL = "url"
    const val DOMAIN = "domain"
    const val PORT = "port"
    const val PATH = "path"
    const val REGISTER_PROCEDURE = "registerProcedure"
    const val PROTOCOL = "protocol"
    const val NAME = "name"
}